[package]
name = "image2ascii"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
egui = "0.28"
eframe = "0.28"
rfd = "0.14"
web-sys = {version = ">= 0.3.4, < 0.3.70"}
wasm-bindgen-futures = "0.4"